exec-once = waybar
# exec-once = hyprpaper
exec-once = swww-daemon

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = blueman-applet

# exec-once = discord
exec-once = swaync
