exec-once = waybar
exec-once = awww-daemon

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = blueman-applet

exec-once = swaync
exec-once = discord
exec-once = hypridle
