windowrule {
  name = discord-position
  workspace = 4 silent
  # monitor = HDMI-A-1
  focus_on_activate = on
  match:class=^(discord)$
}

windowrule {
  name = file-float
  float = on
  move = 225 60
  # center = on
  size = 1100 900
  match:class=^(org.gnome.Nautilus)$
}

windowrule {
  name = loupe-image-viewer-float
  float = on
  match:class=^(org.gnome.Loupe)$
}

windowrule {
  name = calculator
  float = on
  size = 360 540
  match:class=^(org.gnome.Calculator)$
}

windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5)), match:class ^(org.gnome.Calculator)$

windowrule {
  name = floating_kitty
  float = on
  move = 385 135
  size = 1150 840
  match:class=(floating_shell)
}

windowrule {
    name = pavucontrol_popup
    float = on
    move = 1200 40
    size = 400 500
    match:class=^(pavucontrol)$
}
