exec-once = $HOME/.config/hypr/initial-boot.sh

$configs = $HOME/.config/hypr/configs # Default Configs directory path

source=$configs/Keybinds.conf # Pre-configured keybinds

# Load defaults, then user additions/overrides
source= $configs/Startup_Apps.conf 

source= $configs/ENVariables.conf # Environment variables (defaults)

# Load defaults, then user additions
source= $configs/WindowRules.conf # Window Rules and Layer Rules (user)
source= $configs/WorkSpaceRules.conf

source= $configs/SystemSettings.conf # Default config for hypr 

source= $configs/Decorations.conf
source= $configs/Animations.conf

# nwg-displays
source= $HOME/.config/hypr/monitors.conf
# source= $HOME/.config/hypr/workspaces.conf
source = ~/.config/hypr/noctalia/noctalia-colors.conf

source = $configs/OverwrideMutugen.conf
