$iDIR="$HOME/.config/swaync/images/ja.png"

general {
    lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 540
    # on-timeout = notify-send -i $iDIR " You are idle!"
    # on-resume = notify-send -i $iDIR " Oh! you're Back" " Hello !!!
}


listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
