general {
    # We remove lock_cmd from here so it doesn't auto-lock
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    # How long to wait AFTER locking (e.g., 60 seconds)
    timeout = 5

    # Check if hyprlock is running. If yes, turn off screen.
    on-timeout = pgrep -x hyprlock && hyprctl dispatch dpms off

    # Always turn screen back on when you move the mouse/type
    on-resume = hyprctl dispatch dpms on
}

listener {
   timeout = 900

   on-timeout = pgrep -x hyprlock || (hyprlock & hyprctl dispatch dpms off)
   on-resume = hyprctl dispatch dpms on
}
