exec-once = $HOME/.config/hypr/initial-boot.sh

$configs = $HOME/.config/hypr/configs
exec-once = $HOME/.config/hypr/scripts/MonitorSetup.sh

# Load monitors
source=$HOME/.config/hypr/monitors.conf

# Load all config files
source=$configs/Keybinds.conf
source=$configs/Startup_Apps.conf
source=$configs/Decorations.conf
source=$configs/WindowRuls.conf
source=$configs/WorkSpaceRuls.conf
source=$configs/SystemSettings.conf
source=$configs/ENVariables.conf
source=$configs/Animations.conf
source=$configs/CTL.conf
