-- Monitor configuration (was monitors.conf)
--
-- Heads up: monitors.conf was generated by nwg-displays, which writes the old
-- .conf format. That file is no longer read while hyprland.lua is active, so if
-- you re-run nwg-displays you must port its output here by hand. Each monitor=
-- line "OUTPUT,MODE,POSITION,SCALE" maps to one hl.monitor{} call below.

-- monitor=eDP-2,2560x1600@165.0,0x0,1.6
hl.monitor({ output = "eDP-2",    mode = "2560x1600@165.0", position = "0x0",    scale = 1.6 })

-- monitor=HDMI-A-1,1920x1080@144.0,1600x0,1.0
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@144.0", position = "1600x0", scale = 1.0 })

-- monitor=DP-1,1920x1080@60.0,3520x0,1.0
hl.monitor({ output = "DP-1",     mode = "1920x1080@60.0",  position = "3520x0", scale = 1.0 })
