font_family Lilex Nerd Font
font_size 13
bold_font auto
modify_font cell_height 110%
disable_ligatures always
italic_font auto
bold_italic_font auto

background_opacity 1
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1
cursor_blink_interval 0

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 2 6

include themes/tokyo-night.conf
# bamboo
# background #252623 
# nordic
# background #242933
# dark theme
# background #131313
# catpuccin macchiato
# background #24273a
