env = EDITOR,nvim

# Define preferred text editor for the KooL Quick Settings Menu (SUPER SHIFT E)
# script will take the default EDITOR and nano as fallback
$edit=${EDITOR:-nano}

# These two are for UserKeybinds.conf & Waybar Modules
$term = kitty # Terminal
$files = nautilus # File Manager

# Default Search Engine for ROFI Search (SUPER S)
$Search_Engine = "https://www.google.com/search?q={}"

